# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [107]:
import numpy as np
import pandas as pd

## Importing the dataset

In [108]:
dataset = pd.read_csv('../data/mldata.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

def conv(phrase):
    t = 0
    multiplier = 10 ** (len(phrase) - 1)
    notes = ['','S','r','R','g','G','M','m','P','d','D','n','N']
    for n in phrase:
        t += notes.index(n) * multiplier
        multiplier /= 10
    return t
import guessRaga as g
from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# ym = le.fit_transform(y)
ym = []
print(g.RAGAS)
for d in y:
    ym.append(g.RAGAS.index(d.strip()))
ym = np.array(ym)
print(ym[:20])
print(list(ym).index(61))
for v in range(len(X[:, 0])):
    X[v, :][0] = conv(X[v, :][0])

print(X[:20, :])


['Abhogi', 'Adana', 'Ahir Bhairav', 'Amritvarshini', 'Bageshree', 'Bageshrikauns', 'Bahaar', 'Bairagi', 'Barawa', 'Basant', 'Bhairav', 'Bhairavi', 'Bhatiyar', 'Bhimpalasi', 'Bhinna Shadja', 'Bhoopali', 'Bhoopali Todi', 'Bibhas', 'Bihag', 'Bihagda', 'Bilaskhani Todi', 'Bilawal', 'Vrindavani Sarang', 'Chandrakauns', 'Charukeshi', 'Chhayanat', 'Darbari Kanada', 'Des', 'Dhani', 'Durga', 'Gorakh Kalyan', 'Gaud Malhar', 'Gujari Todi', 'Gunakali', 'Hameer', 'Hansadhwani', 'Hindol', 'Janasammohini', 'Jaijaivanti', 'Jait', 'Jog', 'Jogkauns', 'Jogiya', 'Jaunpuri', 'Kafi', 'Kalavati', 'Kalingada', 'Kamod', 'Kedar', 'Kirvani', 'Khamaj', 'Kolahas', 'Lalat', 'Madmaad Sarang', 'Madhukauns', 'Madhuvanti', 'Malkauns', 'Malhar', 'Mand', 'Marwa', 'Marubihag', 'Multani', 'Nand', 'Nat Bhairav', 'Nayaki Kanada', 'Paraj', 'Parameshwari', 'Patadeep', 'Pooriya', 'Pooriya Kalyan', 'Pooriya Dhanashree', 'Poorvi', 'Rageshri', 'Rajakalyan', 'Ramadasimalhar', 'Ramakali', 'Salag Varali', 'Saraswati', 'Shahanakanada'

## Splitting the dataset into the Training set and Test set

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, ym, test_size = 0.05, random_state = 0)

In [110]:
print(X_train)

[[64631.0]
 [40878.0]
 [28462.0]
 ...
 [52689.0]
 [86906.0]
 [90208.0]]


In [111]:
print(y_train[14])

8


In [112]:
print(X_test)

[[102987.0]
 [25898.0]
 [59011.0]
 [86911.0]
 [52307.0]
 [87905.0]
 [24904.0]
 [120921.0]
 [78757.0]
 [131211.0]
 [68590.0]
 [86631.0]
 [12285.0]
 [22490.0]
 [58360.0]
 [123582.0]
 [13422.0]
 [43643.0]
 [79287.0]
 [47921.0]
 [119018.0]
 [56516.0]
 [56873.0]
 [23019.0]
 [85833.0]
 [55702.0]
 [75212.0]
 [108661.0]
 [32201.0]
 [18742.0]
 [35689.0]
 [70843.0]
 [49111.0]
 [101370.0]
 [57130.0]
 [112063.0]
 [111158.0]
 [129864.0]
 [82489.0]
 [85835.0]
 [23032.0]
 [87866.0]
 [11592.0]
 [35912.0]
 [12585.0]
 [22063.0]
 [68633.0]
 [125901.0]
 [78568.0]
 [37905.0]
 [129749.0]
 [20878.0]
 [13429.0]
 [128751.0]
 [59020.0]
 [36370.0]
 [22851.0]
 [44701.0]
 [32256.0]
 [91346.0]
 [125135.0]
 [120633.0]
 [85858.0]
 [125689.0]
 [38531.0]
 [32092.0]
 [90651.0]
 [35923.0]
 [65313.0]
 [52572.0]
 [53531.0]
 [125631.0]
 [34911.0]
 [92088.0]
 [22971.0]
 [13683.0]
 [64218.0]
 [109085.0]
 [83920.0]
 [64315.0]
 [69221.0]
 [33658.0]
 [108122.0]
 [75725.0]
 [68922.0]
 [22979.0]
 [33075.0]
 [47987.0]
 [66535.0]
 [

In [113]:
print(y_test)

[65 17 15 13 36 25 76 19  9 34 31  7 35 76 79 73 11  8  3 55  1 93 25 41
 79 41 81  2  8 61 24  8 51 30 14 30 45 49 16 79 65 25 79 21 17 30 30 82
 18 47 32 18 11  3 15 30 35  0 52 49 88 30 31 10 15 47  4 35 24 68 79 34
 51 25 32  1 28 19 57  8 22  8 59 68 42 52 59 90 27 59 41 32  1 81 93 38
  7 25 11 23 60 57 93 10 62 65 51  9 25 36 29 62 79 92 10 25 47 26 13 55
  9 11 57  7  0 32  2 18 25 14 73 65 11 39 25 81  8 12 79 14 75 41 87 65
  8 79 51 18 67 11 50  3 72  8 25 30 59 12 51 83 88  6  8 32  6  1 52 41
 25 26 17 25 47  7 19  8 79 55 11 70 60  8 72 62 57  6  8 27  2 49 16 62
  6 61 31 57  8 26 75 68 11 27  8 60 79 41 22 65 34  5 66 31 26 74 55 43
  8 25 25  5 20 93 40 33 27 18 18  2 11 85 11 29 10  9 38 86 57  7  2 87
 68  1  8 25  3 65  3 18  7 79 18 72 60 68 85 18 12 25 41 11 29 19 54 54
 75 88 20 11 30 15 41 10 62  2 32 27 15 30  4 34 44  2 15 58]


## Feature Scaling

In [114]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train.reshape(-1, 1))
X_test = sc.transform(X_test.reshape(-1, 1))

In [115]:
print(X_train)

[[-0.17095638]
 [-0.85009531]
 [-1.20509   ]
 ...
 [-0.5123986 ]
 [ 0.465924  ]
 [ 0.56033383]]


In [116]:
print(X_test)

[[ 0.92570731]
 [-1.27839915]
 [-0.3316418 ]
 [ 0.46606695]
 [-0.52332064]
 [ 0.49448712]
 [-1.30681931]
 [ 1.43847107]
 [ 0.23293014]
 [ 1.73267978]
 [-0.0577618 ]
 [ 0.45806127]
 [-1.66761812]
 [-1.3758397 ]
 [-0.35025501]
 [ 1.51455361]
 [-1.63510935]
 [-0.77103923]
 [ 0.24808374]
 [-0.64872388]
 [ 1.38406104]
 [-0.40297812]
 [-0.39277088]
 [-1.36071469]
 [ 0.43524509]
 [-0.42625178]
 [ 0.13157252]
 [ 1.08793668]
 [-1.09818559]
 [-1.48300144]
 [-0.9984577 ]
 [ 0.00665533]
 [-0.61469975]
 [ 0.87947451]
 [-0.38542281]
 [ 1.18520569]
 [ 1.15933019]
 [ 1.69416675]
 [ 0.33963441]
 [ 0.43530227]
 [-1.360343  ]
 [ 0.49337204]
 [-1.68743218]
 [-0.99208175]
 [-1.65904061]
 [-1.38804837]
 [-0.05653235]
 [ 1.58085779]
 [ 0.2275263 ]
 [-0.93509847]
 [ 1.6908787 ]
 [-1.42192954]
 [-1.6349092 ]
 [ 1.66234417]
 [-0.33138448]
 [-0.97898675]
 [-1.3655181 ]
 [-0.7407892 ]
 [-1.09661305]
 [ 0.5928712 ]
 [ 1.55895654]
 [ 1.43023666]
 [ 0.43595988]
 [ 1.57479635]
 [-0.91720006]
 [-1.10130209]
 [ 0.57299

## Training the K-NN model on the Training set

In [117]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1, metric = 'minkowski', p = 2)
knn.fit(X_train.reshape(-1, 1), y_train.reshape(-1, 1))

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Predicting a new result

In [118]:

def conv(phrase):
    t = 0
    multiplier = 10 ** (len(phrase) - 1)
    notes = ['','S','r','R','g','G','M','m','P','d','D','n','N']
    for n in phrase:
        t += notes.index(n) * multiplier
        multiplier /= 10
    return t
phrase = input('Please enter a phrase: ')
def validate(phrase):
    if len(phrase) == 0:
        guesses =  'Your phrase is empty.'
    for note in phrase:
        if note not in 'SrRgGMmPdDnN- ':
            guesses =  'Your phrase has a letter which is not a note. Please reenter your phrase.'
    while '-' in phrase:
       phrase = phrase.replace('-', '')
    if len(phrase) < 5:
        guesses = 'Your phrase is too short. Please enter a longer phrase.'
    return phrase

    
phrase = validate(phrase)
print(rfc.predict(sc.transform([[conv(phrase)]])))
print(y[list(ym).index(int(rfc.predict(sc.transform([[conv(phrase)]]))))])
print(RAGAS[rfc.predict(sc.transform([[conv(phrase)]]))[0]])

[34]
 Hameer
Hameer


## Predicting the Test set results

In [119]:
y_predknn = knn.predict(X_test)
print(np.concatenate((y_predknn.reshape(len(y_predknn),1), y_test.reshape(len(y_test),1)),1))

y_predrfc = rfc.predict(X_test)
print(np.concatenate((y_predrfc.reshape(len(y_predrfc),1), y_test.reshape(len(y_test),1)),1))

[[65 65]
 [17 17]
 [24 15]
 [ 2 13]
 [14 36]
 [25 25]
 [76 76]
 [21 19]
 [65  9]
 [21 34]
 [18 31]
 [ 7  7]
 [ 3 35]
 [16 76]
 [79 79]
 [73 73]
 [11 11]
 [26  8]
 [61  3]
 [54 55]
 [75  1]
 [88 93]
 [25 25]
 [41 41]
 [79 79]
 [18 41]
 [ 9 81]
 [12  2]
 [26  8]
 [54 61]
 [25 24]
 [19  8]
 [76 51]
 [ 8 30]
 [62 14]
 [ 5 30]
 [ 4 45]
 [49 49]
 [76 16]
 [79 79]
 [65 65]
 [25 25]
 [45 79]
 [37 21]
 [17 17]
 [66 30]
 [30 30]
 [21 82]
 [75 18]
 [47 47]
 [81 32]
 [60 18]
 [11 11]
 [70  3]
 [10 15]
 [30 30]
 [35 35]
 [11  0]
 [70 52]
 [11 49]
 [38 88]
 [30 30]
 [ 8 31]
 [58 10]
 [34 15]
 [ 2 47]
 [88  4]
 [35 35]
 [18 24]
 [ 2 68]
 [21 79]
 [10 34]
 [51 51]
 [77 25]
 [32 32]
 [43  1]
 [20 28]
 [31 19]
 [31 57]
 [ 4  8]
 [18 22]
 [26  8]
 [36 59]
 [68 68]
 [33 42]
 [32 52]
 [59 59]
 [32 90]
 [38 27]
 [59 59]
 [41 41]
 [32 32]
 [78  1]
 [75 81]
 [93 93]
 [38 38]
 [31  7]
 [55 25]
 [13 11]
 [32 23]
 [60 60]
 [31 57]
 [ 8 93]
 [75 10]
 [31 62]
 [65 65]
 [ 0 51]
 [ 9  9]
 [47 25]
 [14 36]
 [24 29]
 

## Making the Confusion Matrix

In [120]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predknn)
print(cm)
accuracy_score(y_test, y_predknn)



[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 2 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 2]]


0.33098591549295775

In [121]:
t, c = 0, 0
print(len(y_test), len(y_predknn))
for y in y_test:
    t += 1
    yp = y_predrfc[list(y_test).index(y)]
    if y == yp:
        c += 1
print(t, c, c/t)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predrfc)
print(cm)

    
accuracy_score(y_test, y_predrfc)

284 284
284 105 0.36971830985915494
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 3 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 2]]


0.3380281690140845